#' prepare_qfeature
#'
#' assemble qfeature object from all of the matricies generated by the pipeline
#'
#' @param pg_matrix_fp
#' @param pr_matrix_fp
#' @param superkingdom_matrix_fp
#' @param kingdom_matrix_fp
#' @param phylum_matrix_fp
#' @param class_matrix_fp
#' @param order_matrix_fp
#' @param family_matrix_fp
#' @param genus_matrix_fp
#' @param species_matrix_fp
#' @param go_matrix_fp
#'
#' @returns
#' @export
#'
#' @examples
prepare_qfeature <- function(pg_matrix_fp,
                             pr_matrix_fp,
                             superkingdom_matrix_fp,
                             kingdom_matrix_fp,
                             phylum_matrix_fp,
                             class_matrix_fp,
                             order_matrix_fp,
                             family_matrix_fp,
                             genus_matrix_fp,
                             species_matrix_fp,
                             go_matrix_fp) {

  # Read the protein group matrix
  pg_matrix <- readr::read_tsv(pg_matrix_fp)

  # Extract quantitative columns
  quantCols <- colnames(pg_matrix)[grepl(".*raw.*", colnames(pg_matrix))]

  # Create initial QFeatures object
  QF <- QFeatures::readQFeatures(pg_matrix, quantCols = quantCols, name = "ProteinGroups")

  # Read all taxonomy-based matrices into a named list
  taxonomy_files <- list(
    superkingdom = superkingdom_matrix_fp,
    kingdom = kingdom_matrix_fp,
    phylum = phylum_matrix_fp,
    class = class_matrix_fp,
    order = order_matrix_fp,
    family = family_matrix_fp,
    genus = genus_matrix_fp,
    species = species_matrix_fp
  )

  # Read and store each taxonomy matrix into the QFeatures object
  for (tax_level in names(taxonomy_files)) {
    tax_matrix <- readr::read_tsv(taxonomy_files[[tax_level]],na = "NA")

    # Convert to SummarizedExperiment before adding to QFeatures
    tax_assay <- QFeatures::readSummarizedExperiment(tax_matrix,
                                                     quantCols =  quantCols)

    # Add to QFeatures object
    QF <- QFeatures::addAssay(QF, tax_assay, name = tax_level)
  }

  # Read and store go_matrix into the QFeatures object
  go_matrix <- readr::read_tsv(go_matrix_fp, na = "NA")

  go_assay <- QFeatures::readSummarizedExperiment(go_matrix,
                                                  quantCols =  quantCols)

  QF <- QFeatures::addAssay(QF, go_assay, name = "go_description")


  return(QF)
}
